apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: churn-api
  template:
    metadata:
      labels:
        app: churn-api
    spec:
      containers:
      - name: churn-api
        image: churn-api:latest # Replace with your image repo if pushing to registry
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: model-volume
          mountPath: /app/models
      volumes:
      - name: model-volume
        hostPath:
          path: /absolute/path/to/your/models # Change to your actual model path
          type: Directory
